# **Chapter 7: Data Cleaning and Preparation**

## **7.1 Handling Missing Data**

In [1]:
import pandas as pd
import numpy as np

In [2]:
string_data = pd.Series(["aardvark", "artichoke", np.nan, "avocado"])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### **Filtering Out Missing Data**

In [7]:
from numpy import nan as NA # NA = np.nan

In [8]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])

In [12]:
cleaned = data.dropna()

In [13]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4] = NA

In [17]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [18]:
data.dropna(axis=1, how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
df = pd.DataFrame(np.random.randn(7, 3))

In [20]:
df.iloc[:4, 1] = NA

In [21]:
df.iloc[:2, 2] = NA

In [22]:
df

0         1         2
0  2.373172       NaN       NaN
1  0.348719       NaN       NaN
2  0.181519       NaN  1.656317
3 -0.850795       NaN -0.111106
4 -0.616640 -0.344578  0.716242
5  0.474941 -0.271513 -1.238169
6 -0.082841  1.179857 -0.358875

In [23]:
df.dropna()

0         1         2
4 -0.616640 -0.344578  0.716242
5  0.474941 -0.271513 -1.238169
6 -0.082841  1.179857 -0.358875

In [24]:
df.dropna(thresh=2) #en az 2 dolu değer içeren satırlar harici kalanları düşür.

0         1         2
2  0.181519       NaN  1.656317
3 -0.850795       NaN -0.111106
4 -0.616640 -0.344578  0.716242
5  0.474941 -0.271513 -1.238169
6 -0.082841  1.179857 -0.358875

## **Filling In Missing Data**

In [25]:
df

0         1         2
0  2.373172       NaN       NaN
1  0.348719       NaN       NaN
2  0.181519       NaN  1.656317
3 -0.850795       NaN -0.111106
4 -0.616640 -0.344578  0.716242
5  0.474941 -0.271513 -1.238169
6 -0.082841  1.179857 -0.358875

In [26]:
df.fillna(0)

0         1         2
0  2.373172  0.000000  0.000000
1  0.348719  0.000000  0.000000
2  0.181519  0.000000  1.656317
3 -0.850795  0.000000 -0.111106
4 -0.616640 -0.344578  0.716242
5  0.474941 -0.271513 -1.238169
6 -0.082841  1.179857 -0.358875

In [27]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  2.373172  0.500000  0.000000
1  0.348719  0.500000  0.000000
2  0.181519  0.500000  1.656317
3 -0.850795  0.500000 -0.111106
4 -0.616640 -0.344578  0.716242
5  0.474941 -0.271513 -1.238169
6 -0.082841  1.179857 -0.358875

In [28]:
_ = df.fillna(0, inplace=True)

In [29]:
df

0         1         2
0  2.373172  0.000000  0.000000
1  0.348719  0.000000  0.000000
2  0.181519  0.000000  1.656317
3 -0.850795  0.000000 -0.111106
4 -0.616640 -0.344578  0.716242
5  0.474941 -0.271513 -1.238169
6 -0.082841  1.179857 -0.358875

In [30]:
df = pd.DataFrame(np.random.randn(6, 3))

In [31]:
df.iloc[2:, 1] = NA

In [32]:
df.iloc[4:, 2] = NA

In [33]:
df

0         1         2
0 -0.683804 -0.734925 -0.227225
1  0.508230 -0.626476 -1.806783
2  0.263232       NaN  2.077399
3  0.580721       NaN -1.226255
4 -1.031545       NaN       NaN
5  0.311897       NaN       NaN

In [34]:
df.fillna(method="ffill")

0         1         2
0 -0.683804 -0.734925 -0.227225
1  0.508230 -0.626476 -1.806783
2  0.263232 -0.626476  2.077399
3  0.580721 -0.626476 -1.226255
4 -1.031545 -0.626476 -1.226255
5  0.311897 -0.626476 -1.226255

In [35]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [36]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [37]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## **7.2 Data Transformation**

### **Removing Duplicates**

In [38]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],'k2': [1, 1, 2, 3, 3, 4, 4]})

In [39]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [41]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [42]:
data['v1'] = range(7)

In [43]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [44]:
data.drop_duplicates(["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [46]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### **Transforming Data Using a Function or Mapping**

In [47]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                                          'Pastrami', 'corned beef', 'Bacon',
                                          'pastrami', 'honey ham', 'nova lox'],
                                             'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [48]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [49]:
meat_to_animal = {
 'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'
}

In [50]:
lowercased = data["food"].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [51]:
data["animal"] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [52]:
data["food"].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### **Replacing Values**

In [53]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [56]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [58]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [59]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [61]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), 
                   index = ['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [63]:
transform = lambda x: x[:4].upper()

In [64]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [65]:
data.index = data.index.map(transform)

In [66]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [67]:
data.rename(index = str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [68]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [69]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [70]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### **Discretization and Binning**

In [71]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [72]:
bins = [18, 25, 35, 60, 100]

In [73]:
cats = pd.cut(ages, bins)

In [74]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [75]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [76]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [78]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [79]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [80]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [81]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [82]:
data = np.random.randn(20)

In [83]:
pd.cut(data, 4, precision=2)

[(-1.49, -0.5], (0.5, 1.5], (0.5, 1.5], (-0.5, 0.5], (-2.49, -1.49], ..., (0.5, 1.5], (-0.5, 0.5], (0.5, 1.5], (0.5, 1.5], (-2.49, -1.49]]
Length: 20
Categories (4, interval[float64]): [(-2.49, -1.49] < (-1.49, -0.5] < (-0.5, 0.5] < (0.5, 1.5]]

In [84]:
 data = np.random.randn(1000) # Normally distributed

In [85]:
cats = pd.qcut(data, 4) # Cut into quartiles

In [86]:
cats

[(-0.6, 0.0337], (0.715, 3.53], (0.715, 3.53], (-3.598, -0.6], (-3.598, -0.6], ..., (-3.598, -0.6], (0.715, 3.53], (-3.598, -0.6], (-3.598, -0.6], (-3.598, -0.6]]
Length: 1000
Categories (4, interval[float64]): [(-3.598, -0.6] < (-0.6, 0.0337] < (0.0337, 0.715] < (0.715, 3.53]]

In [87]:
pd.value_counts(cats)

(0.715, 3.53]      250
(0.0337, 0.715]    250
(-0.6, 0.0337]     250
(-3.598, -0.6]     250
dtype: int64

In [88]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.214, 0.0337], (0.0337, 1.386], (0.0337, 1.386], (-1.214, 0.0337], (-1.214, 0.0337], ..., (-1.214, 0.0337], (0.0337, 1.386], (-1.214, 0.0337], (-1.214, 0.0337], (-1.214, 0.0337]]
Length: 1000
Categories (4, interval[float64]): [(-3.598, -1.214] < (-1.214, 0.0337] < (0.0337, 1.386] < (1.386, 3.53]]

### **Detecting and Filtering Outliers**

In [89]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [91]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.027657     0.018820     0.008607     0.008674
std       1.008678     1.059026     0.996736     0.988062
min      -3.274468    -3.316690    -2.858923    -2.847481
25%      -0.703789    -0.664153    -0.637866    -0.658564
50%      -0.009627     0.029212    -0.009816    -0.030003
75%       0.635100     0.746421     0.679534     0.651626
max       2.825809     3.877610     3.619500     3.549539

In [92]:
col = data[2]

In [93]:
col

0      0.055768
1     -0.935291
2      0.017554
3     -0.912438
4     -0.236736
         ...   
995   -0.334779
996   -0.434797
997   -0.713844
998   -0.372203
999    1.078444
Name: 2, Length: 1000, dtype: float64

In [94]:
col[np.abs(col)>3]

67     3.077452
200    3.619500
371    3.405282
902    3.043092
Name: 2, dtype: float64

In [95]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
46  -0.367148 -1.846761 -2.288855  3.117103
67  -0.312776  2.169552  3.077452  1.049327
107 -0.973933 -3.316690 -0.189275  0.267887
139  1.958991  3.877610  0.132290  0.495977
200  0.537462  1.276613  3.619500 -0.291457
341 -3.274468 -0.089315  1.586669  1.429120
371  0.299003 -0.370724  3.405282  0.490031
544 -0.222282 -0.669133 -0.342156  3.348172
639  0.357391  1.899392 -0.155666  3.549539
902  0.282683  1.380988  3.043092 -0.759066
983  0.774868  3.123931 -0.505228 -1.383702

In [96]:
data[np.abs(data) > 3] = np.sign(data)*3

In [97]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.027383     0.018135     0.007462     0.007660
std       1.007831     1.054873     0.993008     0.984759
min      -3.000000    -3.000000    -2.858923    -2.847481
25%      -0.703789    -0.664153    -0.637866    -0.658564
50%      -0.009627     0.029212    -0.009816    -0.030003
75%       0.635100     0.746421     0.679534     0.651626
max       2.825809     3.000000     3.000000     3.000000

In [98]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0 -1.0
1 -1.0 -1.0 -1.0 -1.0
2  1.0  1.0  1.0  1.0
3  1.0 -1.0 -1.0 -1.0
4 -1.0  1.0 -1.0 -1.0

### **Permutation and Random Sampling**

In [99]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [100]:
sampler = np.random.permutation(5)

In [101]:
sampler

array([2, 3, 1, 4, 0])

In [102]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [103]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7
4  16  17  18  19
0   0   1   2   3

In [104]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [105]:
choices = pd.Series([5, 7, -1, 6, 4])

In [107]:
draws = choices.sample(n=10, replace=True)
draws

3    6
1    7
3    6
0    5
0    5
4    4
3    6
4    4
0    5
3    6
dtype: int64

### **Computing Indicator/Dummy Variables**

In [108]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})

In [109]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [110]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [111]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [114]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [112]:
df_with_dummy = df[["data1"]].join(dummies)

In [113]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [115]:
mnames = ['movie_id', 'title', 'genres']

In [116]:
movies  = pd.read_table("../datasets/movielens/movies.dat", sep="::", header=None, names=mnames)

/home/recepaydogdu/.local/lib/python3.8/site-packages/pandas/io/parsers.py:767: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())


In [117]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [118]:
all_genres = []

In [119]:
for x in movies.genres:
    all_genres.extend(x.split("|"))

In [120]:
genres = pd.unique(all_genres)

In [121]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [122]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [123]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [124]:
gen = movies.genres[0]

In [125]:
gen.split("|")

['Animation', "Children's", 'Comedy']

In [126]:
dummies.columns.get_indexer(gen.split("|"))

array([0, 1, 2])

In [127]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split("|"))
    dummies.iloc[i, indices] = 1

In [130]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [131]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [132]:
np.random.seed(12345)

In [133]:
values = np.random.rand(10)

In [134]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [135]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [136]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## **7.3 String Manipulation**