# **Appendix A: Advanced Numpy**

## **A.1 ndarray Object Internals**

In [2]:
import numpy as np

In [3]:
np.ones((10, 5)).shape

(10, 5)

In [4]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

### **NumPy dtype Hierarchy**

In [5]:
 ints = np.ones(10, dtype=np.uint16)

In [6]:
floats = np.ones(10, dtype=np.float32)

In [7]:
np.issubdtype(ints.dtype, np.integer)

True

In [8]:
np.issubdtype(floats.dtype, np.floating)

True

In [9]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [10]:
np.issubdtype(ints.dtype, np.number)

True

## **A.2 Advanced Array Manipulation**

### **Reshaping Arrays**

In [11]:
arr = np.arange(8)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
 arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [14]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
arr = np.arange(15)

In [16]:
 arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
other_arr = np.ones((3, 5))

In [18]:
other_arr.shape

(3, 5)

In [19]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
arr = np.arange(15).reshape((5, 3))

In [21]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
 arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])